#Showing the lstrip(), rstrip(), and strip()
a = ("\tJohn Paul likes python \n")
print("\n")
print("using a to print")
print(a)
print("\nlstrip()")
print(a.lstrip())
print("\nrstrip()")
print(a.rstrip())
print("\nstrip()")
print(a.strip())
print("\n")